Feature/add static analysis  (#23)
Add static analysis

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -40,7 +40,7 @@ jobs:
       - uses: actions/checkout@v3
 
       # Runs a set of commands using the runners shell
-      - name: Unit Tests GCC
+      - name: Unit Tests GCC Release
         run: |
           cmake -S . -B build -G Ninja -D CMAKE_BUILD_TYPE=Release -D CMAKE_BUILD_TYPE=Debug
           cmake --build build --target all -j $(nproc)
@@ -76,11 +76,57 @@ jobs:
       - uses: actions/checkout@v3
 
       # Runs a set of commands using the runners shell
-      - name: Unit Tests Clang
+      - name: Unit Tests Clang Release
         run: |
           cmake -S . -B build -G Ninja -D CMAKE_BUILD_TYPE=Release -D CMAKE_C_COMPILER=clang -D CMAKE_CXX_COMPILER=clang++
           cmake --build build --target all -j $(nproc)
           cd build && ctest --output-on-failure
+
+  clang-tidy:
+    # The type of runner that the job will run on (has to be ubuntu for docker)
+    runs-on: ubuntu-latest
+    # The image tag to use for the container
+    container: mmmtastymmm/cpp-tooling-build-enviornment
+    # Steps represent a sequence of tasks that will be executed as part of the job
+    steps:
+      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+      - uses: actions/checkout@v3
+
+      # Runs a set of commands using the runners shell
+      - name: Clang Tidy
+        run: |
+          cmake -S . -B build -G Ninja -D CMAKE_BUILD_TYPE=Release -D CMAKE_C_COMPILER=clang -D CMAKE_CXX_COMPILER=clang++
+          run-clang-tidy -j $(nproc) -p build -export-fixes clang-tidy-fixes.yml
+          if [ -s clang-tidy-fixes.yml ]; then
+            # The file is not-empty.
+            echo "There are clang tidy errors to apply, use clang-apply-replacements to apply any changes that can be applied."
+            exit 1
+          else
+            echo "There were no issues"
+          fi
+      - uses: actions/upload-artifact@v3
+        name: 'Upload Clang Issues'
+        if: ${{ failure() }}
+        with:
+          name: clang-tidy-fixes
+          path: clang-tidy-fixes.yml
+          retention-days: 2
+
+  cppcheck:
+    # The type of runner that the job will run on (has to be ubuntu for docker)
+    runs-on: ubuntu-latest
+    # The image tag to use for the container
+    container: mmmtastymmm/cpp-tooling-build-enviornment
+    # Steps represent a sequence of tasks that will be executed as part of the job
+    steps:
+      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+      - uses: actions/checkout@v3
+
+      # Runs a set of commands using the runners shell
+      - name: CPP Check
+        run: |
+          cmake -S . -B build -G Ninja -D CMAKE_BUILD_TYPE=Debug -D BUILD_TESTS=OFF
+          cppcheck --project=build/compile_commands.json --suppressions-list=suppression_files/cppcheck.txt
 
   # Test with the unit tests Clang
   format-code:
@@ -94,7 +140,7 @@ jobs:
       - uses: actions/checkout@v3
 
       # Runs a set of commands using the runners shell
-      - name: Format C++ and CMake
+      - name: Check Correct Format for C++ Files and CMake Files
         run: |
           git config --global --add safe.directory /__w/Cpp-Tooling/Cpp-Tooling
           cmake -S . -B build -G Ninja -D CMAKE_BUILD_TYPE=Debug
