Feature/add unittest framework (#17)
Adding unit test framework, ensure sanitizers are working correctly

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -11,7 +11,7 @@ on:
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
   # Test with the unit tests GCC
-  build_and_unit_tests:
+  build-and-unit-tests:
     # The type of runner that the job will run on (has to be ubuntu for docker)
     runs-on: ubuntu-latest
     # The image tag to use for the container
@@ -24,14 +24,31 @@ jobs:
       # Runs a set of commands using the runners shell
       - name: Unit Tests GCC
         run: |
-          mkdir build
-          cd build
-          cmake -G Ninja ..
-          cmake --build . --target all
-          ctest --output-on-failure
+          cmake -S . -B build -G Ninja -D CMAKE_BUILD_TYPE=Debug
+          cmake --build build --target all
+          cd build && ctest --output-on-failure
+
+    # Test with the unit tests GCC
+  build-and-unit-tests-release:
+    # The type of runner that the job will run on (has to be ubuntu for docker)
+    runs-on: ubuntu-latest
+    # The image tag to use for the container
+    container: mmmtastymmm/cpp-tooling-build-enviornment
+    # Steps represent a sequence of tasks that will be executed as part of the job
+    steps:
+      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+      - uses: actions/checkout@v3
+
+      # Runs a set of commands using the runners shell
+      - name: Unit Tests GCC
+        run: |
+          cmake -S . -B build -G Ninja -D CMAKE_BUILD_TYPE=Release -D CMAKE_BUILD_TYPE=Debug
+          cmake --build build --target all
+          cd build && ctest --output-on-failure
+
 
   # Test with the unit tests Clang
-  build_and_unit_tests_clang:
+  build-and-unit-tests-clang-debug:
     # The type of runner that the job will run on (has to be ubuntu for docker)
     runs-on: ubuntu-latest
     # The image tag to use for the container
@@ -44,11 +61,26 @@ jobs:
       # Runs a set of commands using the runners shell
       - name: Unit Tests Clang
         run: |
-          mkdir build
-          cd build
-          cmake -G Ninja -D CMAKE_C_COMPILER=clang -D CMAKE_CXX_COMPILER=clang++ ..
-          cmake --build . --target all
-          ctest --output-on-failure
+          cmake -S . -B build -G Ninja -D CMAKE_BUILD_TYPE=Debug -D CMAKE_C_COMPILER=clang -D CMAKE_CXX_COMPILER=clang++
+          cmake --build build --target all
+          cd build && ctest --output-on-failure
+
+  build-and-unit-tests-clang-release:
+    # The type of runner that the job will run on (has to be ubuntu for docker)
+    runs-on: ubuntu-latest
+    # The image tag to use for the container
+    container: mmmtastymmm/cpp-tooling-build-enviornment
+    # Steps represent a sequence of tasks that will be executed as part of the job
+    steps:
+      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+      - uses: actions/checkout@v3
+
+      # Runs a set of commands using the runners shell
+      - name: Unit Tests Clang
+        run: |
+          cmake -S . -B build -G Ninja -D CMAKE_BUILD_TYPE=Release -D CMAKE_C_COMPILER=clang -D CMAKE_CXX_COMPILER=clang++
+          cmake --build build --target all
+          cd build && ctest --output-on-failure
 
   # Test with the unit tests Clang
   format-code:
@@ -65,7 +97,7 @@ jobs:
       - name: Format C++ and CMake
         run: |
           git config --global --add safe.directory /__w/Cpp-Tooling/Cpp-Tooling
-          cmake -S . -B build -G Ninja
+          cmake -S . -B build -G Ninja -D CMAKE_BUILD_TYPE=Debug
           cmake --build build --target check-format
 
   # Test with the unit tests Address Sanitizer
@@ -158,3 +190,33 @@ jobs:
           cmake --build build --target all
           grep -q "sanitize=memory" build/compile_commands.json
           cd build && ctest --output-on-failure
+
+  no-build-specified:
+    # The type of runner that the job will run on (has to be ubuntu for docker)
+    runs-on: ubuntu-latest
+    # The image tag to use for the container
+    container: mmmtastymmm/cpp-tooling-build-enviornment
+    # Steps represent a sequence of tasks that will be executed as part of the job
+    steps:
+      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+      - uses: actions/checkout@v3
+
+      # Tries to run cmake with no build type, which should fail and thus the OR bash route taken and exit with zero
+      - name: Test
+        run: |
+          cmake -S . -B build -G Ninja && exit 1 || exit 0
+
+  incorrect-build-specified:
+    # The type of runner that the job will run on (has to be ubuntu for docker)
+    runs-on: ubuntu-latest
+    # The image tag to use for the container
+    container: mmmtastymmm/cpp-tooling-build-enviornment
+    # Steps represent a sequence of tasks that will be executed as part of the job
+    steps:
+      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+      - uses: actions/checkout@v3
+
+      # Tries to run cmake with a bad build type, which should fail and thus the OR bash route taken and exit with zero
+      - name: Test
+        run: |
+          cmake -S . -B build -G Ninja -D CMAKE_BUILD_TYPE=BadBuildString && exit 1 || exit 0
